name: Publish Docker Image

env:
  EUREKA_IMAGE: aldeeyar/innometrics-eureka:${{ github.sha }}

on: 
  push:
    branches:
      - 'main'
      - 'ci'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu' # Alternative distribution options are available.
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Eureka - Build JAR file
        working-directory: .
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Eureka - Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.EUREKA_IMAGE }}
          build-args: |
            JAR_FILE=./target/innometrics-eureka-server.jar

  push_to_dokku:
    name: Push to Dokku
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@84.201.135.131:22/innometrics-eureka'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.EUREKA_IMAGE }}